### ISSUE TITLE
smass bayes - output probability?

### ISSUE THREAD

**Issue by walthowd** [jlmcgehee21/smart_hass#3]
Is there any option in smart_hass to output the probability score for a bayesian inference simulation?

I'm running simulations (smass bayes -t -c /tmp/sleeping | json_pp) and knowing the exact score would help the troubleshooting process.

Thank you, and thanks for the great component and tool.

**Comment by jlmcgehee21** [comment]
Currently, there is no way to output the probability -- only list combinations that yield `true` or `false`. I suppose a way to hack it to do this for now, would be to change the threshold on your sensor, and see at what point you have a combination evaluate to `true`

I know that's not super ideal though, so I'll leave this issue open as a feature request, and hopefully get around to adding that option.

Feel free to submit a pull-request if it's critical to your use case.  Otherwise, unfortunately, you will be forced to wait until myself or someone else decides they have the time to commit :)
